# Generated by Django 5.2 on 2025-05-07 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=100)),
                ('file_path', models.FileField(upload_to='music/')),
                ('genre', models.CharField(choices=[('lo-fi', 'Lo-Fi'), ('classical', 'Classical'), ('ambient', 'Ambient'), ('jazz', 'Jazz'), ('nature', 'Nature Sounds')], max_length=50)),
                ('duration', models.IntegerField(default=0)),
            ],
        ),
    ]
