# Generated by Django 5.2 on 2025-05-07 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_musictrack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musictrack',
            name='artist',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='musictrack',
            name='file_path',
            field=models.CharField(max_length=255),
        ),
    ]
