# Generated by Django 5.2 on 2025-05-08 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_alter_musictrack_artist_alter_musictrack_file_path'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MusicTrack',
        ),
    ]
