# Generated by Django 5.2 on 2025-05-07 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='music_genre',
            field=models.CharField(choices=[('lo-fi', 'Lo-Fi'), ('classical', 'Classical'), ('ambient', 'Ambient')], default='lo-fi', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferred_categories',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='DailyStudyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('duration', models.IntegerField(default=0)),
                ('sessions', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'date')},
            },
        ),
    ]
