# Generated by Django 5.2 on 2025-05-08 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_activitylog'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailystudylog',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='dailystudylog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='music_genre',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='preferred_categories',
        ),
        migrations.DeleteModel(
            name='ActivityLog',
        ),
        migrations.DeleteModel(
            name='DailyStudyLog',
        ),
    ]
